import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
test("관리자 로그인과 주민 응답 수직 흐름",async({page,isMobile})=>{
  test.skip(Boolean(isMobile),"공유 시연 응답 원장은 데스크톱에서 한 번 검증하고 모바일은 별도 레이아웃 시나리오로 확인합니다.");
  await page.goto("/admin/login"); await page.getByRole("button",{name:"로그인"}).click(); await expect(page.getByRole("heading",{name:"안건 현황"})).toBeVisible();
  await expect(page.getByRole("heading",{name:"단지별 누적 응답"})).toBeVisible(); await expect(page.getByRole("link",{name:"자료",exact:true})).toHaveCount(0); await expect(page.getByRole("link",{name:"감사 기록"})).toHaveCount(0);
  await page.goto("/admin/agendas"); await expect(page.getByRole("heading",{name:"안건 제작",exact:true})).toBeVisible(); await page.goto("/admin/agendas/demo-agenda"); await page.locator('input[name="file"]').setInputFiles({name:"주차선-변경안.pdf",mimeType:"application/pdf",buffer:Buffer.from("%PDF-1.4\n% HION demo\n")}); await page.locator('input[name="altTextKo"]').fill("변경 전·후 주차선 배치도"); await page.getByRole("button",{name:"안건에 첨부"}).click(); await expect(page.getByText("첨부 자료가 안건에 저장되어 입주민 화면에 공개됩니다.")).toBeVisible();
  await page.goto("/admin/campaigns/demo-campaign/reports"); const csvPromise=page.waitForEvent("download"); await page.getByRole("link",{name:"한국어 CSV 내려받기"}).click(); const csv=await csvPromise; const csvPath=await csv.path(); expect(csvPath&&await readFile(csvPath,"utf8")).toContain("전체 대상"); const pdfPromise=page.waitForEvent("download"); await page.getByRole("link",{name:"한국어 PDF 요약"}).click(); const pdf=await pdfPromise; expect(pdf.suggestedFilename()).toContain("HION");
  await page.goto("/c/demo-parking-change-1203"); await page.getByRole("button",{name:"안건 내용 확인하기"}).click();
  await expect(page.getByRole("heading",{name:"비용 및 관리비 영향"})).toBeVisible(); await expect(page.getByText("9,000원").first()).toBeVisible(); await expect(page.getByRole("heading",{name:"안건 첨부 자료"})).toBeVisible(); await expect(page.getByRole("link",{name:/주차선-변경안.pdf/}).first()).toBeVisible(); await expect(page.getByRole("heading",{name:"3D 모델"})).toBeVisible(); await page.getByRole("button",{name:"안건 내용을 확인했습니다"}).click(); await expect(page.getByRole("button",{name:"기권",exact:true})).toHaveCount(0); await page.getByRole("button",{name:"동의",exact:true}).click(); await page.getByRole("checkbox").check(); await page.getByRole("button",{name:"본인 확인으로 이동"}).click(); await page.getByRole("button",{name:"인증번호 받기"}).click(); await page.getByRole("button",{name:"본인 확인 후 최종 검토"}).click(); await expect(page.getByRole("heading",{name:"선택한 내용을 확인해 주세요"})).toBeVisible(); await page.getByRole("button",{name:"이 의견으로 최종 제출"}).click(); await expect(page.getByRole("heading",{name:"응답 영수증"})).toBeVisible(); await page.goto("/admin"); await expect(page.getByText("825명").first()).toBeVisible();
});
test("문서 언어와 모바일 공식 사이트 레이아웃",async({page})=>{await page.setViewportSize({width:360,height:800});await page.goto("/");await expect(page.locator("html")).toHaveAttribute("lang","ko");await expect(page).toHaveURL(/\/$/);await expect(page.getByRole("heading",{name:/건물의 모든 자산과 운영 데이터를 하나로/})).toBeVisible();await expect(page.getByRole("button",{name:"메뉴 열기"})).toBeVisible();});
test("주요 화면이 기준 너비에서 잘리지 않는다",async({page},testInfo)=>{for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto("/");await expect(page.locator("body")).not.toHaveCSS("overflow-x","scroll");await page.screenshot({path:testInfo.outputPath(`홈-${width}.png`),fullPage:true});}});
