"use client";

import { useState } from "react";
import { feeImportStatusKo, feeImportTypeKo } from "@/lib/fees/presentation";
import { formatWon } from "@/lib/format/ko";

type PreviewBatch = { id:string; type:"ASSESSMENT"|"COLLECTION"; filename:string; encoding:string; rowCount:number; validRowCount:number; warningCount:number; blockingErrorCount:number; sourceTotal:string; calculatedTotal:string; status:"UPLOADED"|"VALIDATED"|"CONFIRMED"|"REJECTED"; issues:Array<{rowNumber:number;column:string|null;severity:"WARNING"|"BLOCKING";codeKo:string;messageKo:string;maskedSummary:string}>; records:Array<Record<string,string>> };
const assessmentTargets=["단지코드","기준월","동","호","항목코드","부과액","외부행ID","원본합계"];
const collectionTargets=["단지코드","기준월","동","호","거래유형","금액","거래일","외부거래번호","원본합계"];

export function FeeImportWizard({ periodId, referenceMonth }: { periodId: string; referenceMonth: string }) {
  const [type,setType]=useState<"ASSESSMENT"|"COLLECTION">("ASSESSMENT");
  const [sourceHeaders,setSourceHeaders]=useState<string[]>(assessmentTargets);
  const [mapping,setMapping]=useState<Record<string,string>>(Object.fromEntries(assessmentTargets.map((item)=>[item,item])));
  const [batch,setBatch]=useState<PreviewBatch|null>(null);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  const targets=type==="ASSESSMENT"?assessmentTargets:collectionTargets;

  function changeType(next:"ASSESSMENT"|"COLLECTION") { const nextTargets=next==="ASSESSMENT"?assessmentTargets:collectionTargets; setType(next); setBatch(null); setSourceHeaders(nextTargets); setMapping(Object.fromEntries(nextTargets.map((item)=>[item,item]))); }
  async function detectHeaders(file:File|undefined){if(!file)return;const text=await file.text();const firstLine=text.replace(/^\uFEFF/,"").split(/\r?\n/,1)[0]??"";const headers=firstLine.split(",").map((item)=>item.trim().replace(/^"|"$/g,"")).filter(Boolean);if(headers.length){setSourceHeaders(headers);setMapping(Object.fromEntries(headers.map((source)=>[source,targets.includes(source)?source:""])));}}
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setMessage("");const form=new FormData(event.currentTarget);form.set("periodId",periodId);form.set("referenceMonth",referenceMonth);form.set("type",type);form.set("columnMapping",JSON.stringify(mapping));const response=await fetch("/api/admin/fees/imports",{method:"POST",body:form});const data=await response.json() as {batch?:PreviewBatch;error?:string};if(!response.ok||!data.batch)setError(data.error??"CSV를 검증하지 못했습니다.");else{setBatch(data.batch);setMessage("행별 검증과 합계 대사가 끝났습니다.");}setBusy(false);}
  async function confirm(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!batch)return;setBusy(true);setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/fees/imports/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({batchId:batch.id,idempotencyKey:crypto.randomUUID(),warningReasonKo:form.get("warningReasonKo")||undefined})});const data=await response.json() as {batch?:{status:PreviewBatch["status"]};error?:string};if(!response.ok||!data.batch)setError(data.error??"등록을 확정하지 못했습니다.");else{setBatch({...batch,status:data.batch.status});setMessage("관리비 데이터를 불변 등록 내역으로 확정했습니다.");}setBusy(false);}

  return <>
    <section className="card"><h2>1. 기준월과 등록 유형</h2><div className="filter-grid"><label>기준월<input className="field" value={referenceMonth} readOnly/></label><label>등록 유형<select className="field" value={type} onChange={(event)=>changeType(event.target.value as typeof type)}><option value="ASSESSMENT">관리비 부과</option><option value="COLLECTION">수납·환급</option></select></label><a className="btn" href={`/api/admin/fees/templates?type=${type}`}>한국어 CSV 양식 내려받기</a></div></section>
    <section className="card" style={{marginTop:16}}><h2>2. CSV 업로드와 원본 열 감지</h2><form onSubmit={upload}><label className="field-label" htmlFor="fee-csv">CSV 파일</label><input className="field" id="fee-csv" name="file" type="file" accept=".csv,text/csv" required onChange={(event)=>void detectHeaders(event.target.files?.[0])}/><h3>3. 열 연결 확인</h3><p className="muted">감지한 원본 CSV 열을 HION 관리비 필드에 연결합니다. 필수 필드가 모두 연결되어야 합니다.</p><div className="table-wrap"><table><thead><tr><th>원본 CSV 열</th><th>HION 관리비 필드</th></tr></thead><tbody>{sourceHeaders.map((source)=><tr key={source}><td>{source}</td><td><select className="field" aria-label={`${source} 열 연결`} value={mapping[source]??""} onChange={(event)=>setMapping({...mapping,[source]:event.target.value})}><option value="">사용하지 않음</option>{targets.map((target)=><option key={target} value={target}>{target}</option>)}</select></td></tr>)}</tbody></table></div><button className="btn btn-primary" style={{marginTop:12}} disabled={busy}>{busy?"검증 중…":"업로드하고 검증"}</button></form></section>
    {batch&&<section className="card" style={{marginTop:16}}><h2>4. 미리보기와 합계 대사</h2><dl><dt>파일</dt><dd>{batch.filename}</dd><dt>인코딩</dt><dd>{batch.encoding}</dd><dt>등록 유형</dt><dd>{feeImportTypeKo(batch.type)}</dd><dt>전체 행</dt><dd>{batch.rowCount.toLocaleString("ko-KR")}행</dd><dt>유효 행</dt><dd>{batch.validRowCount.toLocaleString("ko-KR")}행</dd><dt>원본 합계</dt><dd>{formatWon(batch.sourceTotal)}</dd><dt>계산 합계</dt><dd>{formatWon(batch.calculatedTotal)}</dd><dt>상태</dt><dd>{feeImportStatusKo(batch.status)}</dd></dl>{batch.issues.length>0&&<div className="table-wrap"><table><thead><tr><th>행</th><th>심각도</th><th>코드</th><th>한국어 설명</th><th>마스킹 요약</th></tr></thead><tbody>{batch.issues.map((item,index)=><tr key={`${item.rowNumber}-${index}`}><td>{item.rowNumber}</td><td>{item.severity==="BLOCKING"?"차단 오류":"경고"}</td><td>{item.codeKo}</td><td>{item.messageKo}</td><td>{item.maskedSummary}</td></tr>)}</tbody></table></div>}<h3>앞부분 미리보기</h3><pre className="data-preview">{JSON.stringify(batch.records.slice(0,5),null,2)}</pre>{batch.blockingErrorCount===0&&batch.status!=="CONFIRMED"&&<form onSubmit={confirm}><label className="field-label" htmlFor="warning-reason">경고 확인 사유</label><input className="field" id="warning-reason" name="warningReasonKo" placeholder="경고가 있을 때 확인 사유를 입력해 주세요." required={batch.warningCount>0}/><button className="btn btn-primary" style={{marginTop:12}} disabled={busy}>검증 결과 확인 후 등록 확정</button></form>}</section>}
    {message&&<p className="success" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
  </>;
}
