import { beforeEach, describe, expect, it } from "vitest";
import { FEE_REFERENCE_MONTH, resetFeeDemoStore } from "@/server/demo/fee-store";
import { koreanFeeCsvTemplate, previewFeeImport } from "@/server/services/management-fee-import";

const context={tenantId:"hion-demo",roles:["ACCOUNTING_MANAGER"]};
const bytes=(value:string)=>new TextEncoder().encode(value);
const assessment=(rows:string[])=>`단지코드,기준월,동,호,항목코드,부과액,외부행ID,원본합계\n${rows.join("\n")}`;
const collection=(rows:string[])=>`단지코드,기준월,동,호,거래유형,금액,거래일,외부거래번호,원본합계\n${rows.join("\n")}`;

describe("관리비 CSV 등록 검증",()=>{
  beforeEach(()=>resetFeeDemoStore());
  it("2,000세대 부과 자료를 합리적인 시간 안에 검증한다",async()=>{const rows=Array.from({length:2000},(_,index)=>{const building=101+Math.floor(index/400);const local=index%400;const unit=`${Math.floor(local/10)+1}${String(local%10+1).padStart(2,"0")}`;return `HAEOREUM,${FEE_REFERENCE_MONTH},${building},${unit},GENERAL,185000,LINE-${index},`;});const started=performance.now();const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"2천세대-부과.csv",mimeType:"text/csv",data:bytes(assessment(rows))});expect(batch.validRowCount).toBe(2000);expect(batch.blockingErrorCount).toBe(0);expect(batch.calculatedTotal).toBe(370_000_000n);expect(performance.now()-started).toBeLessThan(5000);});
  it("수납과 환급 거래를 검증한다",async()=>{const csv=collection([`HAEOREUM,${FEE_REFERENCE_MONTH},101,101,수납,180000,2026-07-10,PAY-1,`,`HAEOREUM,${FEE_REFERENCE_MONTH},101,102,환급,10000,2026-07-11,REF-1,`]);const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"COLLECTION",filename:"수납-환급.csv",mimeType:"text/csv",data:bytes(csv)});expect(batch.blockingErrorCount).toBe(0);expect(batch.calculatedTotal).toBe(190_000n);});
  it("같은 파일 해시를 다시 등록하지 않는다",async()=>{const data=bytes(koreanFeeCsvTemplate("ASSESSMENT"));const input={periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT" as const,filename:"부과.csv",mimeType:"text/csv",data};await previewFeeImport(context,input);await expect(previewFeeImport(context,input)).rejects.toThrow("이미 등록");});
  it("중복 부과 행과 중복 거래번호를 차단한다",async()=>{const a=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"중복부과.csv",mimeType:"text/csv",data:bytes(assessment([`HAEOREUM,${FEE_REFERENCE_MONTH},101,101,GENERAL,10000,A-1,`,`HAEOREUM,${FEE_REFERENCE_MONTH},101,101,GENERAL,20000,A-2,`]))});expect(a.issues.some(item=>item.codeKo==="중복 부과 행")).toBe(true);resetFeeDemoStore();const p=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"COLLECTION",filename:"중복수납.csv",mimeType:"text/csv",data:bytes(collection([`HAEOREUM,${FEE_REFERENCE_MONTH},101,101,수납,10000,2026-07-10,P-1,`,`HAEOREUM,${FEE_REFERENCE_MONTH},101,102,수납,20000,2026-07-10,P-1,`]))});expect(p.issues.some(item=>item.codeKo==="중복 거래")).toBe(true);});
  it("존재하지 않는 세대와 다른 단지 자료를 차단한다",async()=>{const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"잘못된세대.csv",mimeType:"text/csv",data:bytes(assessment([`OTHER,${FEE_REFERENCE_MONTH},999,9999,GENERAL,10000,X-1,`]))});expect(batch.blockingErrorCount).toBeGreaterThanOrEqual(2);expect(batch.issues.map(item=>item.codeKo)).toEqual(expect.arrayContaining(["다른 단지 자료","존재하지 않는 세대"]));});
  it("기준월·항목·금액·날짜·인코딩 오류를 한국어로 설명한다",async()=>{const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"형식오류.csv",mimeType:"text/csv",data:bytes(assessment([`HAEOREUM,2026-13,101,101,UNKNOWN,-1,X-1,`]))});expect(batch.issues.map(item=>item.codeKo)).toEqual(expect.arrayContaining(["기준월 오류","알 수 없는 관리비 항목","금액 형식 오류"]));await expect(previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"이진.csv",mimeType:"text/csv",data:new Uint8Array([0,1,2])})).rejects.toThrow("이진 파일");});
  it("원본 합계와 계산 합계 차이를 차단한다",async()=>{const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"합계차이.csv",mimeType:"text/csv",data:bytes(assessment([`HAEOREUM,${FEE_REFERENCE_MONTH},101,101,GENERAL,10000,X-1,9999`]))});expect(batch.issues.some(item=>item.codeKo==="원본 합계 불일치")).toBe(true);});
  it("사용자 정의 원본 열을 HION 필드에 연결한다",async()=>{const csv=`단지,월,건물,세대,코드,청구액,행번호\nHAEOREUM,${FEE_REFERENCE_MONTH},101,101,GENERAL,12000,CUSTOM-1`;const batch=await previewFeeImport(context,{periodId:`fee-period-${FEE_REFERENCE_MONTH}`,referenceMonth:FEE_REFERENCE_MONTH,type:"ASSESSMENT",filename:"사용자열.csv",mimeType:"text/csv",data:bytes(csv),columnMapping:{단지:"단지코드",월:"기준월",건물:"동",세대:"호",코드:"항목코드",청구액:"부과액",행번호:"외부행ID"}});expect(batch.blockingErrorCount).toBe(0);expect(batch.records[0]?.부과액).toBe("12000");});
});
